In [76]:
import pandas as pd
import numpy as np

In [77]:
file_path = '../data/ raw/used_cars_dataset.csv'

In [78]:
df = pd.read_csv(file_path)
df.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
0,Honda,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000"
1,Toyota,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000"
2,Volkswagen,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999"
3,Maruti Suzuki,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000"
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000"

In [79]:
print("Number of rows: ", df.shape[0])
print("Number of columns: ", df.shape[1])

Number of rows:  14993
Number of columns:  11

In [80]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 14993 entries, 0 to 14992
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         14993 non-null  str
 1   model         14993 non-null  str
 2   Year          14993 non-null  int64
 3   Age           14993 non-null  int64
 4   kmDriven      14905 non-null  str
 5   Transmission  14993 non-null  str
 6   Owner         14993 non-null  str
 7   FuelType      14993 non-null  str
 8   PostedDate    14993 non-null  str
 9   AdditionInfo  14993 non-null  str
 10  AskPrice      14993 non-null  str
dtypes: int64(2), str(9)
memory usage: 1.3 MB
None

In [81]:
print("check null values")
print(df.isnull().sum())

check null values
Brand            0
model            0
Year             0
Age              0
kmDriven        88
Transmission     0
Owner            0
FuelType         0
PostedDate       0
AdditionInfo     0
AskPrice         0
dtype: int64

In [82]:
print("check duplicates")
print(df.duplicated().sum())

check duplicates
997

In [83]:
df_cleaned = df.drop_duplicates()
print("Number of rows after removing duplicates: ", df_cleaned.shape[0])

Number of rows after removing duplicates:  13996

In [84]:
from datetime import datetime
now = datetime.now()
df_cleaned['Car_Age'] = now.year - df_cleaned['Year']

In [85]:
df_cleaned.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice,Car_Age
0,Honda,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000",25
1,Toyota,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000",17
2,Volkswagen,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999",16
3,Maruti Suzuki,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000",9
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000",7

In [86]:
df_cleaned = df_cleaned.drop(columns=['Year'], inplace=False)

In [87]:
df_cleaned.head()

,Brand,model,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice,Car_Age
0,Honda,City,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000",25
1,Toyota,Innova,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000",17
2,Volkswagen,VentoTest,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999",16
3,Maruti Suzuki,Swift,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000",9
4,Maruti Suzuki,Baleno,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000",7

In [88]:
df_cleaned.to_csv('../data/processed/used_cars_dataset_cleaned.csv', index=False)